"use client";

import { useState, useEffect, useCallback } from 'react';
import { supabase } from '@/lib/supabase';
import { useAuth } from '@/contexts/AuthContext';
import type { Database } from '@/lib/database.types';
import { generateSmartChatTitle, getBaseChatTitle } from '@/utils/chatTitles';

type Chat = Database['public']['Tables']['chats']['Row'];
type Message = Database['public']['Tables']['messages']['Row'];
type NewChat = Database['public']['Tables']['chats']['Insert'];
type NewMessage = Database['public']['Tables']['messages']['Insert'];

function getErrorMessage(error: unknown): string {
  if (error instanceof Error) {
    return error.message;
  }
  if (typeof error === 'string') {
    return error;
  }
  return 'Unknown error';
}

export function useChats() {
  const { user } = useAuth();
  const [chats, setChats] = useState<Chat[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  const fetchChats = useCallback(async () => {
    if (!user) {
      setChats([]);
      return;
    }

    try {
      setLoading(true);
      const { data, error: queryError } = await supabase
        .from('chats')
        .select('*')
        .eq('user_id', user.id)
        .order('updated_at', { ascending: false });

      if (queryError) throw queryError;
      setChats(data ?? []);
      setError(null);
    } catch (fetchError) {
      setError(getErrorMessage(fetchError));
    } finally {
      setLoading(false);
    }
  }, [user]);

  useEffect(() => {
    if (!user) {
      setChats([]);
      return;
    }

    void fetchChats();

    const subscription = supabase
      .channel('chats-channel')
      .on('postgres_changes', {
        event: '*',
        schema: 'public',
        table: 'chats',
        filter: `user_id=eq.${user.id}`,
      }, () => {
        void fetchChats();
      })
      .subscribe();

    return () => {
      void subscription.unsubscribe();
    };
  }, [user, fetchChats]);

  const createChat = async (title?: string, isAutoGenerated: boolean = true): Promise<Chat | null> => {
    if (!user) return null;

    try {
      const existingTitles = chats.map(chat => getBaseChatTitle(chat.title));
      const finalTitle = title ? 
        generateSmartChatTitle(title, existingTitles) : 
        'New Chat';

      const newChat: NewChat = {
        user_id: user.id,
        title: finalTitle,
        title_auto_generated: isAutoGenerated
      };

      const { data, error } = await supabase
        .from('chats')
        .insert(newChat)
        .select()
        .single();

      if (error) {
        console.error('Database error creating chat:', error);
        return null; // Return null instead of throwing to allow graceful fallback
      }
      
      // Refresh chats list
      await fetchChats();
      return data;
    } catch (creationError) {
      console.error('Failed to create chat:', creationError);
      return null; // Return null instead of throwing to allow graceful fallback
    }
  };

  const updateChatTitle = async (chatId: string, title: string, isManualEdit: boolean = true): Promise<boolean> => {
    try {
      const chat = chats.find(c => c.id === chatId);
      if (!chat) return false;

      // If it's a manual edit, ensure uniqueness
      let finalTitle = title;
      if (isManualEdit) {
        const existingTitles = chats
          .filter(c => c.id !== chatId)
          .map(c => getBaseChatTitle(c.title));
        finalTitle = generateSmartChatTitle(title, existingTitles);
      }

      const { error } = await supabase
        .from('chats')
        .update({ 
          title: finalTitle,
          title_auto_generated: !isManualEdit 
        })
        .eq('id', chatId);

      if (error) throw error;
      
      // Update local state
      setChats(prev => prev.map(chat => 
        chat.id === chatId ? { 
          ...chat, 
          title: finalTitle, 
          title_auto_generated: !isManualEdit 
        } : chat
      ));
      
      return true;
    } catch (updateError) {
      console.error('Failed to update chat title:', updateError);
      return false;
    }
  };

  const generateTitleFromFirstMessage = async (chatId: string, firstMessage: string): Promise<boolean> => {
    try {
      const chat = chats.find(c => c.id === chatId);
      if (!chat || !chat.title_auto_generated) {
        // Don't auto-update if user has manually edited the title
        return false;
      }

      const existingTitles = chats
        .filter(c => c.id !== chatId)
        .map(c => getBaseChatTitle(c.title));
      
      const newTitle = generateSmartChatTitle(firstMessage, existingTitles);
      
      // Only update if the new title is different and meaningful
      if (newTitle !== chat.title && newTitle !== 'New Chat') {
        return await updateChatTitle(chatId, newTitle, false);
      }
      
      return true;
    } catch (titleError) {
      console.error('Failed to generate title from first message:', titleError);
      return false;
    }
  };

  const deleteChat = async (chatId: string): Promise<boolean> => {
    try {
      const { error } = await supabase
        .from('chats')
        .delete()
        .eq('id', chatId);

      if (error) throw error;
      
      // Remove from local state
      setChats(prev => prev.filter(chat => chat.id !== chatId));
      return true;
    } catch (deleteError) {
      setError(getErrorMessage(deleteError));
      return false;
    }
  };

  return {
    chats,
    loading,
    error,
    createChat,
    updateChatTitle,
    generateTitleFromFirstMessage,
    deleteChat,
    refetch: fetchChats
  };
}

export function useMessages(chatId: string | null) {
  const [messages, setMessages] = useState<Message[]>([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const fetchMessages = useCallback(async () => {
    if (!chatId) return;

    try {
      setLoading(true);
      const { data, error: queryError } = await supabase
        .from('messages')
        .select('*')
        .eq('chat_id', chatId)
        .order('created_at', { ascending: true });

      if (queryError) throw queryError;
      setMessages(data ?? []);
      setError(null);
    } catch (fetchError) {
      setError(getErrorMessage(fetchError));
    } finally {
      setLoading(false);
    }
  }, [chatId]);

  useEffect(() => {
    if (!chatId) {
      setMessages([]);
      return;
    }

    void fetchMessages();

    const subscription = supabase
      .channel(`messages-channel-${chatId}`)
      .on('postgres_changes', {
        event: '*',
        schema: 'public',
        table: 'messages',
        filter: `chat_id=eq.${chatId}`,
      }, () => {
        void fetchMessages();
      })
      .subscribe();

    return () => {
      void subscription.unsubscribe();
    };
  }, [chatId, fetchMessages]);

  const addMessage = async (content: string, role: 'user' | 'assistant'): Promise<Message | null> => {
    if (!chatId) return null;

    try {
      const newMessage: NewMessage = {
        chat_id: chatId,
        content,
        role
      };

      const { data, error } = await supabase
        .from('messages')
        .insert(newMessage)
        .select()
        .single();

      if (error) {
        console.error('Database error saving message:', error);
        return null; // Return null instead of throwing to allow graceful fallback
      }
      
      // Update chat's updated_at timestamp
      await supabase
        .from('chats')
        .update({ updated_at: new Date().toISOString() })
        .eq('id', chatId);
      
      return data;
    } catch (insertError) {
      console.error('Failed to save message:', insertError);
      return null; // Return null instead of throwing to allow graceful fallback
    }
  };

  return {
    messages,
    loading,
    error,
    addMessage,
    refetch: fetchMessages
  };
}