/**
 * Utility functions for generating meaningful chat titles from user messages
 */

export interface ChatTitleOptions {
  maxWords?: number;
  maxLength?: number;
  fallbackTitle?: string;
}

/**
 * Generates a meaningful chat title from a user message
 */
export function generateChatTitle(
  message: string, 
  options: ChatTitleOptions = {}
): string {
  const {
    maxWords = 8,
    maxLength = 50,
    fallbackTitle = 'New Chat'
  } = options;

  if (!message || typeof message !== 'string') {
    return fallbackTitle;
  }

  // Clean the message
  const cleanMessage = message
    .trim()
    .replace(/\s+/g, ' ') // Replace multiple spaces with single space
    .replace(/[^\w\s-]/g, '') // Remove special characters except hyphens
    .toLowerCase();

  if (!cleanMessage) {
    return fallbackTitle;
  }

  // Split into words
  const words = cleanMessage.split(' ').filter(word => word.length > 0);
  
  if (words.length === 0) {
    return fallbackTitle;
  }

  // Take first N words
  const titleWords = words.slice(0, maxWords);
  
  // Convert to title case
  const titleCased = titleWords
    .map(word => {
      // Skip common articles, prepositions, and conjunctions unless it's the first word
      const skipWords = ['the', 'a', 'an', 'and', 'or', 'but', 'in', 'on', 'at', 'to', 'for', 'of', 'with', 'by'];
      if (titleWords.indexOf(word) === 0 || !skipWords.includes(word)) {
        return word.charAt(0).toUpperCase() + word.slice(1);
      }
      return word;
    })
    .join(' ');

  // Check length and truncate if necessary
  let title = titleCased;
  if (title.length > maxLength) {
    title = title.substring(0, maxLength - 3).trim() + '...';
  } else if (words.length > maxWords) {
    title = title + '...';
  }

  return title || fallbackTitle;
}

/**
 * Ensures chat title is unique within a list of existing titles
 */
export function ensureUniqueChatTitle(
  baseTitle: string,
  existingTitles: string[]
): string {
  if (!existingTitles.includes(baseTitle)) {
    return baseTitle;
  }

  let counter = 2;
  let uniqueTitle = `${baseTitle} (${counter})`;
  
  while (existingTitles.includes(uniqueTitle)) {
    counter++;
    uniqueTitle = `${baseTitle} (${counter})`;
  }

  return uniqueTitle;
}

/**
 * Checks if a title appears to be auto-generated (not manually edited)
 */
export function isAutoGeneratedTitle(title: string): boolean {
  // Consider it auto-generated if:
  // 1. It's "New Chat" or variations
  // 2. It ends with "..." (truncated)
  // 3. It has the pattern "Title (N)" where N is a number
  
  const newChatPattern = /^new chat(\s*\(\d+\))?$/i;
  const truncatedPattern = /\.{3}$/;
  const numberedPattern = /^.+\s*\(\d+\)$/;
  
  return newChatPattern.test(title) || 
         truncatedPattern.test(title) || 
         numberedPattern.test(title);
}

/**
 * Extracts a clean base title (removes numbering suffix)
 */
export function getBaseChatTitle(title: string): string {
  // Remove numbered suffix like " (2)", " (3)", etc.
  return title.replace(/\s*\(\d+\)$/, '');
}

/**
 * Enhanced chat title generation with context awareness
 */
export function generateSmartChatTitle(
  message: string,
  existingTitles: string[] = [],
  options: ChatTitleOptions = {}
): string {
  const baseTitle = generateChatTitle(message, options);
  return ensureUniqueChatTitle(baseTitle, existingTitles);
}